Repository prography7th/weather-backend, pull requests merged in 2022-06, with the labels that each got.

#74 hotfix: forecast 로깅
  src/forecast/forecast.controller.ts
  src/forecast/forecast.service.ts
Labels: fix

#77 격자좌표 기반 키값으로 데이터 조회하도록 수정
  Dockerfile
  src/batch/batch.interface.ts
  src/batch/batch.service.ts
  src/forecast/forecast.service.ts
  src/users/users.service.ts
Labels: fix

#79 produce service 격자 중복제거 로직 추가
  src/produce/produce.service.ts
Labels: feat, refactor

#80 작업 내용 배포
  src/batch/batch.interface.ts
  src/batch/batch.service.ts
  src/forecast/forecast.service.ts
  src/produce/produce.service.ts
  src/users/users.service.ts
Labels: deploy
