Repository prography7th/weather-backend, pull requests merged in 2022-04, with the labels that each got.

#2 [setting] project initial setting
  .prettierrc
  package-lock.json
  package.json
  src/app.module.ts
  src/common/exceptions/http-exception.filter.ts
  src/common/interceptors/success.interceptor.ts
  src/config/validationSchema.ts
  src/main.ts
  tsconfig.json
Labels: setting

#4 CI/CD 파이프라인 구축
  .dockerignore
  .github/workflows/main.yml
  .gitignore
  Dockerfile
  package-lock.json
  package.json
  src/app.module.ts
Labels: setting

#8 미세먼지 정보 알림 구현
  .gitignore
  package-lock.json
  package.json
  src/app.module.ts
  src/finedust/finedust.helper.ts
  src/finedust/finedust.interface.ts
  src/finedust/finedust.module.ts
  src/finedust/finedust.service.ts
  src/lib/finedust/index.js
  src/lib/finedust/regionBase.js
  src/main.ts
  tsconfig.json
Labels: feat

#10 좌표 행정 구역 변환 모듈 구현
  src/app.module.ts
  src/finedust/finedust.helper.ts
  src/lib/coordinateTransformer/README.md
  src/lib/coordinateTransformer/src/@types/types.d.ts
  src/lib/coordinateTransformer/src/index.js
  src/lib/finedust/README.md
  src/lib/finedust/src/@types/types.d.ts
  src/lib/finedust/src/index.js
  src/lib/finedust/src/regionBase.js
  tsconfig.json
Labels: feat

#12 단기예보 조회 API 구현
  package-lock.json
  package.json
  src/app.module.ts
  src/forecast/forecast.controller.ts
  src/forecast/forecast.interface.ts
  src/forecast/forecast.module.ts
  src/forecast/forecast.service.ts
  tsconfig.json
Labels: feat

#16 지금 날씨 정보 API 구현
  src/forecast/forecast.controller.ts
  src/forecast/forecast.interface.ts
  src/forecast/forecast.service.ts
Labels: feat

#17 중기예보 API 구현
  package.json
  src/app.module.ts
  src/finedust/finedust.service.ts
  src/forecast/forecast.controller.ts
  src/forecast/forecast.module.ts
  src/forecast/forecast.service.ts
  src/forecast/middle-forecast.region-code.ts
  src/forecast/middle-forecast.service.spec.ts
  src/forecast/middle-forecast.service.ts
  src/forecast/rand.region-information.ts
  src/lib/coordinateTransformer/src/@types/types.d.ts
  src/lib/coordinateTransformer/src/index.js
  src/main.ts
Labels: feat

#19 단기예보 baseDate, baseTime 받도록 수정
  src/forecast/forecast.controller.ts
  src/forecast/forecast.service.ts
Labels: refactor

#21 중기 예보 모듈에서 단기 예보 의존성에 의한 수정
  src/forecast/middle-forecast.service.ts
Labels: refactor

#22 날씨 정보 조회 API 배포
  .github/workflows/main.yml
  .gitignore
  .vscode/launch.json
  package-lock.json
  package.json
  src/app.module.ts
  src/finedust/finedust.helper.ts
  src/finedust/finedust.interface.ts
  src/finedust/finedust.module.ts
  src/finedust/finedust.service.ts
  src/forecast/forecast.controller.ts
  src/forecast/forecast.interface.ts
  src/forecast/forecast.module.ts
  src/forecast/forecast.service.ts
  src/forecast/middle-forecast.region-code.ts
  src/forecast/middle-forecast.service.spec.ts
  src/forecast/middle-forecast.service.ts
  src/forecast/rand.region-information.ts
  src/lib/coordinateTransformer/README.md
  src/lib/coordinateTransformer/src/@types/types.d.ts
  src/lib/coordinateTransformer/src/index.js
  src/lib/finedust/README.md
  src/lib/finedust/src/@types/types.d.ts
  src/lib/finedust/src/index.js
  src/lib/finedust/src/regionBase.js
  src/lib/gridCoordinateConverter/src/index.js
  tsconfig.json
Labels: deploy

#24 도커 run 명령어 수정
  .github/workflows/main.yml
Labels: deploy

#27 fix: docker run 수정
  .github/workflows/main.yml
Labels: deploy

#29 유저 API 구현
  src/app.module.ts
  src/forecast/forecast.controller.ts
  src/main.ts
  src/users/dto/save-user.dto.ts
  src/users/dto/update-user.dto.ts
  src/users/dto/user-response.dto.ts
  src/users/entity/user.entity.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: feat

#31 알람 시간 테이블 분리 후 알람 시간 추가, 삭제 기능 구현
  src/app.module.ts
  src/users/dto/update-user.dto.ts
  src/users/dto/user-response.dto.ts
  src/users/entity/alarmTime.entity.ts
  src/users/entity/user.entity.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: feat

#35 알람 시간 seeding
  ormconfig.ts
  package-lock.json
  package.json
  src/app.module.ts
  src/database/seeds/alarmTime.seeder.ts
Labels: feat

#36 행정구역 모듈 구현
  area.csv
  ormconfig.ts
  package-lock.json
  package.json
  src/area/area.module.ts
  src/area/area.service.ts
  src/area/entity/area.entity.ts
  src/database/seeds/alarmTime.seeder.ts
  src/database/seeds/area.seeder.ts
  src/lib/gridCoordinateConverter/src/index.js
  src/users/dto/save-user.dto.ts
  src/users/dto/update-user.dto.ts
  src/users/dto/user-response.dto.ts
  src/users/entity/alarmTime.entity.ts
  src/users/entity/user.entity.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: feat

#38 API 응답 문서 작성
  src/common/decorators/api-response-with-dto.decorator.ts
  src/forecast/dto/middle-info.dto.ts
  src/forecast/dto/now-info.dto.ts
  src/forecast/dto/today-info.dto.ts
  src/forecast/forecast.controller.ts
  src/main.ts
  src/users/dto/save-user.dto.ts
  src/users/dto/update-user.dto.ts
  src/users/dto/user-response.dto.ts
  src/users/entity/alarmTime.entity.ts
  src/users/entity/user.entity.ts
  src/users/users.controller.ts
Labels: docs

#43 now baseDate, baseTime 잘못된 값 들어가는 버그 수정
  src/forecast/forecast.service.ts
Labels: fix
