Repository prography7th/weather-backend, pull requests merged in 2022-05, with the labels that each got.

#47 단기예보 PTY(강수형태)값 추가
  src/forecast/dto/middle-info.dto.ts
  src/forecast/dto/now-info.dto.ts
  src/forecast/dto/today-info.dto.ts
  src/forecast/forecast.controller.ts
  src/forecast/forecast.interface.ts
  src/forecast/forecast.service.ts
Labels: feat

#48 deploy: 작업 내용 배포
  src/area/area.service.ts
  src/forecast/dto/middle-info.dto.ts
  src/forecast/dto/now-info.dto.ts
  src/forecast/dto/today-info.dto.ts
  src/forecast/forecast.controller.ts
  src/forecast/forecast.interface.ts
  src/forecast/forecast.service.ts
Labels: deploy

#49 deploy: 작업 내용 배포
  src/forecast/forecast.service.ts
Labels: deploy

#51 today API 캐싱 데이터 사용하도록 수정
  .github/workflows/main.yml
  package-lock.json
  package.json
  src/app.module.ts
  src/forecast/forecast.controller.ts
  src/forecast/forecast.module.ts
  src/forecast/forecast.service.ts
  src/forecast/middle-forecast.service.ts
Labels: feat

#54 유저 엔티티 컬럼 수정
  src/users/dto/update-user.dto.ts
  src/users/dto/user-response.dto.ts
  src/users/entity/user.entity.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: feat

#55 작업 내용 배포
  .github/workflows/main.yml
  package-lock.json
  package.json
  src/app.module.ts
  src/forecast/forecast.controller.ts
  src/forecast/forecast.module.ts
  src/forecast/forecast.service.ts
  src/forecast/middle-forecast.service.ts
  src/users/dto/update-user.dto.ts
  src/users/dto/user-response.dto.ts
  src/users/entity/user.entity.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: deploy

#56 ElasticCache Redis 캐싱 구현
  package-lock.json
  package.json
  src/app.module.ts
  src/area/area.service.ts
  src/produce/produce.module.ts
  src/produce/produce.service.spec.ts
  src/produce/produce.service.ts
Labels: feat

#60 Firebase 클라우드 메시징 연동하여 푸시 알람 기능 구현
  package-lock.json
  package.json
  src/app.module.ts
  src/batch/batch.interface.ts
  src/batch/batch.module.ts
  src/batch/batch.service.ts
  src/forecast/forecast.module.ts
  src/forecast/forecast.service.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: feat

#62 Redis seeder
  src/finedust/finedust.helper.ts
  src/finedust/finedust.module.ts
  src/produce/produce.module.ts
  src/produce/produce.service.ts
Labels: feat

#63 deploy: 작업 내용 배포
  .github/workflows/main.yml
  src/finedust/finedust.helper.ts
  src/finedust/finedust.module.ts
  src/produce/produce.module.ts
  src/produce/produce.service.ts
Labels: deploy

#66 deploy: 작업 내용 배포
  src/users/users.service.ts
Labels: deploy

#68 caching miss 처리
  src/forecast/forecast.service.ts
Labels: feat, refactor

#69 작업 내용 배포
  src/forecast/forecast.service.ts
Labels: deploy

#71 격자 이벤트 생성으로 수정
  src/produce/produce.service.ts
Labels: fix
