Repository prography7th/weather-backend, pull requests merged in 2022-07, with the labels that each got.

#84 캐싱 요청 시간대 변경
  src/produce/produce.service.ts
Labels: refactor

#87 re-fix message produce time
  src/produce/produce.service.ts
Labels: fix

#88 fix: re-fix message produce time (#87)
  src/produce/produce.service.ts
Labels: deploy

#90 base를 캐시해야하는 날인지 알 수 있도록 구현
  src/produce/produce.service.ts
Labels: feat

#92 어제와 날씨 비교 기능 구현
  src/forecast/dto/now-info.dto.ts
  src/forecast/forecast.interface.ts
  src/forecast/forecast.service.ts
Labels: feat

#93 now API 최고/최저 온도정보 표시 및 null 예외 처리
  src/forecast/dto/now-info.dto.ts
  src/forecast/forecast.service.ts
Labels: refactor

#94 작업 내용 배포
  src/forecast/dto/now-info.dto.ts
  src/forecast/forecast.interface.ts
  src/forecast/forecast.service.ts
  src/produce/produce.service.ts
Labels: deploy
